apiVersion: v1
kind: Secret
metadata:
  name: my-private-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: git@github.com:avp075/kubernetes.git
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAACFwAAAAdzc2gtcn
    NhAAAAAwEAAQAAAgEAmOG19iiVC4/pjfxp2jzxC0OroiEDXtd5z8xmc95iUtm1iLGTR5/L
    4xOhpMmILih3syPadwiFS6IDw/Wbnpyeq55JtIDUdV8uH6D3qM9B/ofTGqcZIBw+H52J9+
    QHZkU4xBVfd2yHHq6+ufKAS3lwFbz8vao0bpSK7uqS6QTGyCei1sIlP1OI3+WCuwV8hbww
    4+O3zcpsI6HczRMsJDDxu3djr6ioH2A94qFjCNUj2UEcX99n4taiaSiQIkW29YHWCoh4C0
    ARAxhaI1lOGqGaO6rIhbP0+wBZzqQeXmuOMNOUd7istl1PuPN5MhnqUL0FHbmWZRikS6Gf
    /V2QttNVl/7MgJpnD9iavhrcx+e4L56uf4+uaJEu3GYzIKw/5i0Hy6SolSZXpfUWKA28M5
    ZHyJTOttWdRgu7I2yIJg5fuPSRavC9j6mZ7jNlqqKBrMDpY7HKNoLDe9XQbcxOjwjGlnXh
    MvEBJOYBwLrbBXTqkbT2yLzpMCGLoCCZCggVvY+gl4DWt+b2M1s1FloRKZWtKek9/Hx85Z
    TTQ/exWmpEIMbPii+0Um7bN1lvgVm1QwNONgtY2KumX2dYwWIKubvN5JDrfZ3qElfD/zAz
    qiUEXrnTM0V5X+Q0YKQyYjf3Wup3JTzL3J1yEcDvgSTtia2a/yOIcLGsFRVtE4Vzr6K22a
    EAAAdQ1/jfitf434oAAAAHc3NoLXJzYQAAAgEAmOG19iiVC4/pjfxp2jzxC0OroiEDXtd5
    z8xmc95iUtm1iLGTR5/L4xOhpMmILih3syPadwiFS6IDw/Wbnpyeq55JtIDUdV8uH6D3qM
    9B/ofTGqcZIBw+H52J9+QHZkU4xBVfd2yHHq6+ufKAS3lwFbz8vao0bpSK7uqS6QTGyCei
    1sIlP1OI3+WCuwV8hbww4+O3zcpsI6HczRMsJDDxu3djr6ioH2A94qFjCNUj2UEcX99n4t
    aiaSiQIkW29YHWCoh4C0ARAxhaI1lOGqGaO6rIhbP0+wBZzqQeXmuOMNOUd7istl1PuPN5
    MhnqUL0FHbmWZRikS6Gf/V2QttNVl/7MgJpnD9iavhrcx+e4L56uf4+uaJEu3GYzIKw/5i
    0Hy6SolSZXpfUWKA28M5ZHyJTOttWdRgu7I2yIJg5fuPSRavC9j6mZ7jNlqqKBrMDpY7HK
    NoLDe9XQbcxOjwjGlnXhMvEBJOYBwLrbBXTqkbT2yLzpMCGLoCCZCggVvY+gl4DWt+b2M1
    s1FloRKZWtKek9/Hx85ZTTQ/exWmpEIMbPii+0Um7bN1lvgVm1QwNONgtY2KumX2dYwWIK
    ubvN5JDrfZ3qElfD/zAzqiUEXrnTM0V5X+Q0YKQyYjf3Wup3JTzL3J1yEcDvgSTtia2a/y
    OIcLGsFRVtE4Vzr6K22aEAAAADAQABAAACAAM3G4TkXnqYVavRmT8QkSv4yc46iiPrbZWZ
    BZZWIOyfxSdtXyTma6MAY6HX5nYcjiRpio+ecXG5VAGR+7pwri5bMU8DVtyLUniyMaU2ay
    uVixM8XI0aJPUUos1AqaZtKiQHFEt6YAbdW1flLY0wzhJ595mMT+cbtwaObsWpbt4QpdZF
    DeQcn1RAoyDIbTGRlzhivpfMlBzFe6OhPaha8mmMOa+tARCsXS7UELVzyJnKCpUKWXiqBY
    9HPe1HmLEGAJS3ASnQ6I6va11jFF8/YvNSbJ5RviMtgyYDOfuHwO0+VOj17IV3Fc00qynK
    ZVz6dbYl5B+nDpUD3p3VMv0CWbJk4CrItI7lxl3EU9EhZx3D3PkCzgs4M/nTGddgMsfbIw
    U/GH8oONozlaDr1rS9nQpqLc5bWKYh1xOHfUgcmBCNuQBwI3BKIbTYkMMAWuGI3v17QnCL
    18en+UfarNczMeNg5I3dE2Qflnxnxbq0o5n2ha/LfdG1vHOcuCfkWd4UN92qPS31mq5Mh5
    R451KhLFR9EnxxazyeS7D6HdJlz3MNBuTRr8cYJiF0qGXRZHB3yH9oS1Yhcdd4r/1E7NXp
    4S4jCdUBts3zy54ozCO2xRHe14uSyGDEqnx9kWbTtvDz7JDc0VeKxFUwj97i1b43CjmsUG
    k80a8C0v7XL9G65sSRAAABAAzT3U59v6Z2+zOawWjHCH9KxABzXGgk5I+n0x2LDAtSBMAz
    d6hSeay8+b3uuoUYvVE6qxB92S3Z418MYD2r5Bt7UyMMqVMSbEZX4Ch8wT+x+udjfdwCnh
    w/KXEgmoDrUahr7mVe7/3X3iJkO6IxlvL85n8MdAlrN2bDyPoM+61lFSJp1sobudorxZ1y
    3RTPG0ArB0PBGinKt7K8ooyqAeN/fm7VuIADS8dY8gbiu18XF23Su4/IS04R7tWycttRkF
    S1T7D0NYa0ZDYjWEp1z7PJzRjJoe2eYS6Wokt6ktZEQJ53HiZvfvJQsTC6Cvsv/VGFM9l9
    oXzBkEPfK+aptbIAAAEBANKl7p18fQRGNKJ56XuHJeBe6LEEbzxW4WqWILayeH43X1ydwC
    XUfPcWx2k13hRLbSQ7WNewZs+euLMCh+Y9TbH7P4pJM4zBm/wBkwXqlXVqcACPiCg2BcCG
    0EH6DLWMdoOP6zvZztCY+qN5NyqMXQUKz1CtNCREVNuYcXI8ikklu14YZCjAiTu8JLowYp
    V/ccjAgH3kjSHRdmuRkNzfiIOhKbFo68hy21K/FcjzhN3TNz8zMTyepiiQ60EodWdbAb3z
    LKZv11gu6PuebR2F7T2RNA60kZoy0n/z2rXRo2gRE7fRPWKKQ+zL0MswvSEzDGi5+x7UST
    MVLs4LOsXYznEAAAEBALnL7OrBWDn1jKBoct1lsoiIDYCjKrnJ8NKmuGu+Sio2DY77hSFi
    tKQuHKKY6noe/czqDVHvJriqS7fT0QBdu9O6TMKLLA1uBvd3fTLERKYGcwZeRg7OJLgeYg
    JTI6brOHI1R4tQ7U9laJt72/F11UoleEf1yShTxytGV4HkT5hyCTcBesyLDPnNbe4oHcwl
    SOPjLsUWqULJSf2BhAo2LOOels5CJ6o1Tzz2YHvNY4NdLDmUofXa8UAWia4Iu3YzPuhhs1
    bdKUD4lzmrg0bkiUyKK6Lr8JthTpw/qcojpIUTp1MAbdPnebXmYglz+1vn2EFYAloybnhM
    piveXegjtjEAAAAVYXJnb2NkQGxvY2FsaG9zdDo4MDgwAQIDBAUG
    -----END OPENSSH PRIVATE KEY-----
