apiVersion: v1
kind: Secret
metadata:
  name: my-private-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: git@github.com:avp075/kubernetes.git
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    
    -----END OPENSSH PRIVATE KEY-----
