apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: sonarqube
    releaseName: sonarqube
    namespace: sonarqube
    version: 0.1.0
    repo: "https://github.com/your-github-user/your-helm-repo.git"  
    valuesFile: ./values/dev/values.yaml  # Specify the values file

resources: []