# Default values for sonarqube.
namespace: sonarqube

# SonarQube Docker image
image:
  repository: sonarqube
  tag: community
  pullPolicy: IfNotPresent

# SonarQube configurations
sonar:
  db:
    type: postgres  # Or your preferred DB type
    host: "sonarqube-db"
    port: 5432
    name: sonar
    username: sonar
    password: sonar_password  # Set your database password here

# Service settings
service:
  type: ClusterIP
  port: 9000

# Ingress configuration
ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: sonarqube.local
      paths:
        - /

# Resources for SonarQube
resources: {}

