apiVersion: v1
kind: Service
metadata:
  name: nexus-service
spec:
  selector:
    app: nexus
  type: NodePort
  ports:
  - nodePort: 31001
    port: 8081
    targetPort: 8081
    
# minikube service sonarqube-service
