apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarqube-deployment
  labels:
    app: sonarqube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarqube
  template:
    metadata:
      labels:
        app: sonarqube
    spec:
      initContainers:
      - name: sysctl
        image: sonarqube:10.4-community
        securityContext:
          privileged: true
          runAsUser: 0
        command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
      containers:
      - name: sonarqube
        image: sonarqube:10.4-community
        env:
        - name: SONAR_JDBC_URL
          valueFrom:
            configMapKeyRef:
              name: sonarqube-configmap
              key: JDBC_URL
        - name: SONAR_JDBC_USERNAME
          valueFrom:
            secretKeyRef:
              name: sonarqube-secret
              key: JDBC_USERNAME
        - name: SONAR_JDBC_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sonarqube-secret
              key: JDBC_PASSWORD
        ports:
        - containerPort: 9000
        imagePullPolicy: IfNotPresent


#After the editing postgresql.conf	 and pg_hba.conf restart postgresql server: sudo service postgresql restart	
#docker run -d --name sonar-postgres -e POSTGRES_USER=sonar -e POSTGRES_PASSWORD=sonar  -p 5432:5432 postgres