apiVersion: v1
kind: Service
metadata:
  name: sonarqube-service
spec:
  selector:
    app: sonarqube
  type: NodePort
  ports:
  - nodePort: 31000
    port: 9000
    targetPort: 9000
# minikube service sonarqube-service
