apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-sonarqube
  namespace: {{ .Values.namespace }}  # Set the namespace explicitly
  labels:
    app: sonarqube
spec:
  selector:
    app: sonarqube
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 9000
  type: {{ .Values.service.type }}

