apiVersion: v1
kind: Secret
metadata:
  name: jenkins-admin-password
  namespace: {{ .Release.Namespace }}
  labels:
    app: jenkins
type: Opaque
data:
  password: {{ .Values.jenkinsAdminPassword | b64enc | quote }}