apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarqube-deployment
  labels:
    app: sonarqube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarqube
  template:
    metadata:
      labels:
        app: sonarqube
    spec:
      initContainers:
      - name: sysctl
        image: sonarqube:10.4-community
        securityContext:
          privileged: true
          runAsUser: 0
        command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
      containers:
      - name: sonarqube
        image: sonarqube:10.4-community
        env:
        - name: SONAR_JDBC_URL
          value: jdbc:postgresql://172.24.47.198:5432/sonar
        - name: SONAR_JDBC_USERNAME
          value: sonar
        - name: SONAR_JDBC_PASSWORD
          value: admin
        ports:
        - containerPort: 9000
        imagePullPolicy: IfNotPresent
